### ISSUE TITLE
Blank screen from WebRepo

### ISSUE THREAD

**Issue by Bri-G** [steppers/codea-community-repo#1]
As reported in Codea forum. All I get is a blank screen from the WebRepo when run on my iPad.

Message in tool window output - “Codea Web Repositry is running as expected”.

p.s. what is the ‘mime’ file required.

**Comment by steppers** [comment]
As mentioned on the forum this appears to be resolved after installing the 1.1 build from Github instead.

Closing.

**Comment by steppers** [comment]
As for the ‘mime’ requirement, that’s used to provide a base64 binary decoder which we need to decode some data from Github. It seems it’s available from LuaSocket.
